#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Graveyard_Tracker.Resource", IsApplication=true)]

namespace Graveyard_Tracker
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activity_vertical_margin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fab_margin = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int nav_header_height = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int nav_header_vertical_spacing = 2130837508;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int ic_menu_camera = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ic_menu_gallery = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ic_menu_manage = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ic_menu_send = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int ic_menu_share = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int ic_menu_slideshow = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int side_nav_bar = 2130903046;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int action_settings = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int drawer_layout = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int fab = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int nav_camera = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int nav_gallery = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int nav_manage = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int nav_send = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int nav_share = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int nav_slideshow = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int nav_view = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int toolbar = 2130968586;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_main = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_bar_main = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int content_main = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int nav_header_main = 2131034115;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int activity_main_drawer = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int menu_main = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_launcher = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_launcher_foreground = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_launcher_round = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int action_settings = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int navigation_drawer_close = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int navigation_drawer_open = 2131230723;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int AppTheme_AppBarOverlay = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int AppTheme_NoActionBar = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int AppTheme_PopupOverlay = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
